---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks: 
    - pause:
        prompt: "Enter password"
        echo: no
      when: password is undefined
      register: password_input

    - set_fact:
        password: "{{ password_input.user_input }}"
      when: password is undefined

    - pause:
        prompt: "Enter random number for aws instance "
        echo: yes
      when: count is undefined
      register: count_input

    - set_fact:
        count: "{{ count_input.user_input }}"
      when: count is undefined  

    - ec2_vpc_net_info:
        region: us-east-1
        filters:
          "tag:Name": ansible-{{ count }}
      register: ansible_vpc

    - ec2_vpc_subnet_info:
        region: us-east-1
        filters:
          vpc-id: "{{ ansible_vpc.vpcs[0].id }}"
      register: ansible_subnet

    - name: linux security group
      ec2_group:
        name: linux-{{ count }}
        description: linux sg
        vpc_id: "{{ ansible_vpc.vpcs[0].id }}"
        region: us-east-1
        tags:
          Name: linux-{{ count }}
          app: ansible-{{ count }}
          env: dev
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80

    - name: create a new ec2 key
      ec2_key:
        name: aws-ansible-key-{{ count }}
        region: us-east-1
        state: present
      register: ec2_key

    # - pause:
    #     prompt: "Enter path for pem key file. Start with ./ and End with .pem"
    #     echo: yes
    #   when: pemfile is undefined
    #   register: pemfile_input

    # - set_fact:
    #     pemfile: "{{ pemfile_input.user_input }}"
    #   when: pemfile is undefined  

    - name: Save private key to disk
      copy: content="{{ ec2_key.key.private_key }}" dest="./aws-ansible-key-{{ count }}.pem" mode=0600
      when: ec2_key.changed

    - name: linux - create ec2 instance
      ec2:
        key_name: aws-ansible-key-{{ count }}
        instance_type: t2.micro
        image: ami-0c322300a1dd5dc79
        region: us-east-1
        group: linux-{{count }}
        count: 1
        vpc_subnet_id: "{{ ansible_subnet.subnets[0].id }}"
        user_data: |
          #!/bin/bash
          sudo adduser ansible
          sudo echo "{{ password }}" | passwd --stdin ansible
          echo 'ansible        ALL=(ALL)       NOPASSWD: ALL' >> /etc/sudoers
          sudo sed -n 'H;${x;s/\PasswordAuthentication no/PasswordAuthentication yes/;p;}' /etc/ssh/sshd_config > tmp_sshd_config
          sudo cat tmp_sshd_config > /etc/ssh/sshd_config
          rm -f tmp_sshd_config
          sudo service sshd restart
        wait: yes
        assign_public_ip: yes
        instance_tags:
          Name: ansible-linux-web-{{ count }}
          app: ansible-{{ count }}
          env: dev
          os: linux
      register: ec2

    - name: associate new elastic IPs with each of the instances
      ec2_eip:
        device_id: "{{ item }}"
        region: us-east-1
        release_on_disassociation: yes
      loop: "{{ ec2.instance_ids }}"